### PR TITLE
fix @most/multicast dependency

### PR DESCRIPTION
**Pull request by maxhoffmann**
Sorry @TylorS! My last PR did not fix the issue as I added `@most/multicast` to `devDependencies`. This PR fixes this.

### CODE REVIEW

**Comment by TylorS** [comment]
I'm wonder if it should be a dependency or a peerDependency; Any thoughts?

**Comment by TylorS** [comment]
I ended up adding it as a peer dependency in #12; If you think this is incorrect, feel free to discuss it further here or in another issue :)

**Comment by TylorS** [comment]
Also publish as v3.0.2

**Comment by maxhoffmann** [comment]
Thanks! :)

**Pull request closed without merging**
